/**
 * Generated API types live in hospici-api.d.ts (auto-generated by openapi-typescript).
 * Run: pnpm generate:types
 *
 * DO NOT manually edit hospici-api.d.ts — it is overwritten on every run.
 * DO commit hospici-api.d.ts to version control so type errors are caught in CI
 * before the backend and frontend are deployed together.
 */

// Re-export commonly used types here as the API grows:
// export type { paths, components } from "./hospici-api";
