#!/usr/bin/env node
/**
 * hospici-review setup script
 * Run once from your repo root: node .claude/skills/hospici-review/scripts/setup.js
 *
 * This will:
 * 1. Copy bootstrap rules into learned-rules.yaml
 * 2. Install git pre-commit hook
 * 3. Create REVIEW_LOG.md if not present
 * 4. Add /review slash command to CLAUDE.md
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const REPO_ROOT = process.cwd();
const SKILL_DIR = path.join(REPO_ROOT, '.claude', 'skills', 'hospici-review');

// ── 1. Bootstrap learned-rules.yaml ─────────────────────────────────────────
console.log('📚 Initializing knowledge base from bootstrap rules...');

const bootstrapPath = path.join(SKILL_DIR, 'references', 'bootstrap-rules.md');
const learnedPath = path.join(SKILL_DIR, 'references', 'learned-rules.yaml');

if (!fs.existsSync(bootstrapPath)) {
  console.error('❌ bootstrap-rules.md not found at', bootstrapPath);
  process.exit(1);
}

// Parse bootstrap rules from markdown code blocks (yaml blocks)
const bootstrapContent = fs.readFileSync(bootstrapPath, 'utf8');
const yamlBlocks = [...bootstrapContent.matchAll(/```yaml\n([\s\S]*?)```/g)].map(m => m[1]);
const allRules = yamlBlocks.flatMap(block => {
  // Extract individual rule objects (simple extraction — Claude will manage full YAML)
  return block.split(/\n- id:/).filter(Boolean).map((r, i) => (i === 0 ? r : '- id:' + r));
}).filter(r => r.trim().startsWith('- id:'));

const initializedYaml = `# Hospici Learned Rules
# Auto-managed by hospici-review skill.
# Last initialized: ${new Date().toISOString()}

rules:
${allRules.join('\n')}

meta:
  initialized: true
  last_run: null
  total_rules_ever: ${allRules.length}
  active_rules: ${allRules.length}
  archived_rules: 0
`;

fs.writeFileSync(learnedPath, initializedYaml);
console.log(`✅ Loaded ${allRules.length} bootstrap rules into learned-rules.yaml`);

// ── 2. Install pre-commit hook ───────────────────────────────────────────────
console.log('🪝  Installing git pre-commit hook...');

const hooksDir = path.join(REPO_ROOT, '.git', 'hooks');
const hookPath = path.join(hooksDir, 'pre-commit');

const hookScript = `#!/bin/sh
# Hospici pre-commit review hook
# Runs hospici-review on staged files before commit
# Critical findings will block the commit.

echo "🏥 Running Hospici pre-commit review..."

# Run Claude Code with hospici-review skill on staged files
# Requires: claude CLI installed and authenticated
if command -v claude &> /dev/null; then
  STAGED=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\\.(ts|tsx|sql)$')
  if [ -n "$STAGED" ]; then
    claude -p "/review $STAGED --pre-commit" 2>&1
    EXIT_CODE=$?
    if [ $EXIT_CODE -ne 0 ]; then
      echo "❌ Critical issues found. Commit blocked. Run '/review' for details."
      exit 1
    fi
  fi
fi

exit 0
`;

if (!fs.existsSync(hooksDir)) {
  console.warn('⚠️  .git/hooks directory not found — skipping hook install');
} else {
  fs.writeFileSync(hookPath, hookScript);
  fs.chmodSync(hookPath, '755');
  console.log('✅ Pre-commit hook installed at .git/hooks/pre-commit');
}

// ── 3. Create REVIEW_LOG.md ──────────────────────────────────────────────────
const reviewLogPath = path.join(REPO_ROOT, 'REVIEW_LOG.md');
if (!fs.existsSync(reviewLogPath)) {
  fs.writeFileSync(reviewLogPath, `# Hospici Review Log\n\nAuto-generated by hospici-review skill.\n\n---\n`);
  console.log('✅ Created REVIEW_LOG.md');
} else {
  console.log('ℹ️  REVIEW_LOG.md already exists — skipping');
}

// ── 4. Register slash command in CLAUDE.md ───────────────────────────────────
const claudeMdPath = path.join(REPO_ROOT, 'CLAUDE.md');
const reviewCommand = `
## Slash Commands

### /review [path] [--fix] [--rules] [--archive] [--reset-rules]
Runs the hospici-review skill.
- No args: full repo scan
- \`[path]\`: scan specific directory or file
- \`--fix\`: attempt auto-fix, learn new rule
- \`--rules\`: list all active learned rules
- \`--archive\`: show archived rules
- \`--reset-rules\`: prompt before clearing knowledge base
`;

if (fs.existsSync(claudeMdPath)) {
  const existing = fs.readFileSync(claudeMdPath, 'utf8');
  if (!existing.includes('/review')) {
    fs.appendFileSync(claudeMdPath, reviewCommand);
    console.log('✅ Added /review slash command to CLAUDE.md');
  } else {
    console.log('ℹ️  /review already in CLAUDE.md — skipping');
  }
} else {
  fs.writeFileSync(claudeMdPath, `# Hospici\n${reviewCommand}`);
  console.log('✅ Created CLAUDE.md with /review command');
}

console.log('\n🎉 Hospici review skill setup complete!\n');
console.log('Next steps:');
console.log('  • Add to CI: claude -p "/review" in your pipeline');
console.log('  • Add cron: 0 9 * * * cd /path/to/repo && claude -p "/review"');
console.log('  • Run first scan: /review');
