/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthedImport } from './routes/_authed'
import { Route as IndexImport } from './routes/index'
import { Route as AuthedDashboardImport } from './routes/_authed/dashboard'
import { Route as AuthedSignaturesIndexImport } from './routes/_authed/signatures/index'
import { Route as AuthedReviewQueueIndexImport } from './routes/_authed/review-queue/index'
import { Route as AuthedQapiIndexImport } from './routes/_authed/qapi/index'
import { Route as AuthedPatientsIndexImport } from './routes/_authed/patients/index'
import { Route as AuthedFilingsIndexImport } from './routes/_authed/filings/index'
import { Route as AuthedChartAuditIndexImport } from './routes/_authed/chart-audit/index'
import { Route as AuthedCapIndexImport } from './routes/_authed/cap/index'
import { Route as AuthedBenefitPeriodsIndexImport } from './routes/_authed/benefit-periods/index'
import { Route as AuthedAlertsIndexImport } from './routes/_authed/alerts/index'
import { Route as AuthedPatientsNewImport } from './routes/_authed/patients/new'
import { Route as AuthedPatientsPatientIdImport } from './routes/_authed/patients/$patientId'
import { Route as AuthedOrdersInboxImport } from './routes/_authed/orders/inbox'
import { Route as AuthedHopeSubmissionsImport } from './routes/_authed/hope/submissions'
import { Route as AuthedHopeDashboardImport } from './routes/_authed/hope/dashboard'
import { Route as AuthedFilingsF2fQueueImport } from './routes/_authed/filings/f2f-queue'
import { Route as AuthedComplianceRecertQueueImport } from './routes/_authed/compliance/recert-queue'
import { Route as AuthedBillingAuditImport } from './routes/_authed/billing/audit'
import { Route as AuthedAnalyticsScorecardsImport } from './routes/_authed/analytics/scorecards'
import { Route as AuthedAnalyticsDeficiencyTrendsImport } from './routes/_authed/analytics/deficiency-trends'
import { Route as AuthedSettingsBaaIndexImport } from './routes/_authed/settings/baa/index'
import { Route as AuthedPatientsPatientIdIndexImport } from './routes/_authed/patients/$patientId/index'
import { Route as AuthedHopeAssessmentsIndexImport } from './routes/_authed/hope/assessments/index'
import { Route as AuthedSettingsBaaNewImport } from './routes/_authed/settings/baa/new'
import { Route as AuthedSettingsBaaIdImport } from './routes/_authed/settings/baa/$id'
import { Route as AuthedPatientsPatientIdTeamCommImport } from './routes/_authed/patients/$patientId/team-comm'
import { Route as AuthedPatientsPatientIdOrdersImport } from './routes/_authed/patients/$patientId/orders'
import { Route as AuthedPatientsPatientIdMedicationsImport } from './routes/_authed/patients/$patientId/medications'
import { Route as AuthedPatientsPatientIdInfoImport } from './routes/_authed/patients/$patientId/info'
import { Route as AuthedPatientsPatientIdDoseSpotImport } from './routes/_authed/patients/$patientId/dose-spot'
import { Route as AuthedPatientsPatientIdDocumentsImport } from './routes/_authed/patients/$patientId/documents'
import { Route as AuthedPatientsPatientIdClinicalNotesImport } from './routes/_authed/patients/$patientId/clinical-notes'
import { Route as AuthedPatientsPatientIdCareTeamImport } from './routes/_authed/patients/$patientId/care-team'
import { Route as AuthedPatientsPatientIdAuditExportImport } from './routes/_authed/patients/$patientId/audit-export'
import { Route as AuthedPatientsPatientIdAssessmentsImport } from './routes/_authed/patients/$patientId/assessments'
import { Route as AuthedHopeAssessmentsNewImport } from './routes/_authed/hope/assessments/new'
import { Route as AuthedHopeAssessmentsIdImport } from './routes/_authed/hope/assessments/$id'
import { Route as AuthedFilingsNoeNewImport } from './routes/_authed/filings/noe/new'
import { Route as AuthedPatientsPatientIdVisitsIndexImport } from './routes/_authed/patients/$patientId/visits/index'
import { Route as AuthedPatientsPatientIdIdgScheduleImport } from './routes/_authed/patients/$patientId/idg/schedule'
import { Route as AuthedPatientsPatientIdF2fNewImport } from './routes/_authed/patients/$patientId/f2f/new'
import { Route as AuthedPatientsPatientIdEncountersEncounterIdVantageChartImport } from './routes/_authed/patients/$patientId/encounters/$encounterId/vantage-chart'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthedDashboardRoute = AuthedDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedSignaturesIndexRoute = AuthedSignaturesIndexImport.update({
  id: '/signatures/',
  path: '/signatures/',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedReviewQueueIndexRoute = AuthedReviewQueueIndexImport.update({
  id: '/review-queue/',
  path: '/review-queue/',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedQapiIndexRoute = AuthedQapiIndexImport.update({
  id: '/qapi/',
  path: '/qapi/',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedPatientsIndexRoute = AuthedPatientsIndexImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedFilingsIndexRoute = AuthedFilingsIndexImport.update({
  id: '/filings/',
  path: '/filings/',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedChartAuditIndexRoute = AuthedChartAuditIndexImport.update({
  id: '/chart-audit/',
  path: '/chart-audit/',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedCapIndexRoute = AuthedCapIndexImport.update({
  id: '/cap/',
  path: '/cap/',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedBenefitPeriodsIndexRoute = AuthedBenefitPeriodsIndexImport.update({
  id: '/benefit-periods/',
  path: '/benefit-periods/',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedAlertsIndexRoute = AuthedAlertsIndexImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedPatientsNewRoute = AuthedPatientsNewImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedPatientsPatientIdRoute = AuthedPatientsPatientIdImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedOrdersInboxRoute = AuthedOrdersInboxImport.update({
  id: '/orders/inbox',
  path: '/orders/inbox',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedHopeSubmissionsRoute = AuthedHopeSubmissionsImport.update({
  id: '/hope/submissions',
  path: '/hope/submissions',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedHopeDashboardRoute = AuthedHopeDashboardImport.update({
  id: '/hope/dashboard',
  path: '/hope/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedFilingsF2fQueueRoute = AuthedFilingsF2fQueueImport.update({
  id: '/filings/f2f-queue',
  path: '/filings/f2f-queue',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedComplianceRecertQueueRoute =
  AuthedComplianceRecertQueueImport.update({
    id: '/compliance/recert-queue',
    path: '/compliance/recert-queue',
    getParentRoute: () => AuthedRoute,
  } as any)

const AuthedBillingAuditRoute = AuthedBillingAuditImport.update({
  id: '/billing/audit',
  path: '/billing/audit',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedAnalyticsScorecardsRoute = AuthedAnalyticsScorecardsImport.update({
  id: '/analytics/scorecards',
  path: '/analytics/scorecards',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedAnalyticsDeficiencyTrendsRoute =
  AuthedAnalyticsDeficiencyTrendsImport.update({
    id: '/analytics/deficiency-trends',
    path: '/analytics/deficiency-trends',
    getParentRoute: () => AuthedRoute,
  } as any)

const AuthedSettingsBaaIndexRoute = AuthedSettingsBaaIndexImport.update({
  id: '/settings/baa/',
  path: '/settings/baa/',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedPatientsPatientIdIndexRoute =
  AuthedPatientsPatientIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedPatientsPatientIdRoute,
  } as any)

const AuthedHopeAssessmentsIndexRoute = AuthedHopeAssessmentsIndexImport.update(
  {
    id: '/hope/assessments/',
    path: '/hope/assessments/',
    getParentRoute: () => AuthedRoute,
  } as any,
)

const AuthedSettingsBaaNewRoute = AuthedSettingsBaaNewImport.update({
  id: '/settings/baa/new',
  path: '/settings/baa/new',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedSettingsBaaIdRoute = AuthedSettingsBaaIdImport.update({
  id: '/settings/baa/$id',
  path: '/settings/baa/$id',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedPatientsPatientIdTeamCommRoute =
  AuthedPatientsPatientIdTeamCommImport.update({
    id: '/team-comm',
    path: '/team-comm',
    getParentRoute: () => AuthedPatientsPatientIdRoute,
  } as any)

const AuthedPatientsPatientIdOrdersRoute =
  AuthedPatientsPatientIdOrdersImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthedPatientsPatientIdRoute,
  } as any)

const AuthedPatientsPatientIdMedicationsRoute =
  AuthedPatientsPatientIdMedicationsImport.update({
    id: '/medications',
    path: '/medications',
    getParentRoute: () => AuthedPatientsPatientIdRoute,
  } as any)

const AuthedPatientsPatientIdInfoRoute =
  AuthedPatientsPatientIdInfoImport.update({
    id: '/info',
    path: '/info',
    getParentRoute: () => AuthedPatientsPatientIdRoute,
  } as any)

const AuthedPatientsPatientIdDoseSpotRoute =
  AuthedPatientsPatientIdDoseSpotImport.update({
    id: '/dose-spot',
    path: '/dose-spot',
    getParentRoute: () => AuthedPatientsPatientIdRoute,
  } as any)

const AuthedPatientsPatientIdDocumentsRoute =
  AuthedPatientsPatientIdDocumentsImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthedPatientsPatientIdRoute,
  } as any)

const AuthedPatientsPatientIdClinicalNotesRoute =
  AuthedPatientsPatientIdClinicalNotesImport.update({
    id: '/clinical-notes',
    path: '/clinical-notes',
    getParentRoute: () => AuthedPatientsPatientIdRoute,
  } as any)

const AuthedPatientsPatientIdCareTeamRoute =
  AuthedPatientsPatientIdCareTeamImport.update({
    id: '/care-team',
    path: '/care-team',
    getParentRoute: () => AuthedPatientsPatientIdRoute,
  } as any)

const AuthedPatientsPatientIdAuditExportRoute =
  AuthedPatientsPatientIdAuditExportImport.update({
    id: '/audit-export',
    path: '/audit-export',
    getParentRoute: () => AuthedPatientsPatientIdRoute,
  } as any)

const AuthedPatientsPatientIdAssessmentsRoute =
  AuthedPatientsPatientIdAssessmentsImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthedPatientsPatientIdRoute,
  } as any)

const AuthedHopeAssessmentsNewRoute = AuthedHopeAssessmentsNewImport.update({
  id: '/hope/assessments/new',
  path: '/hope/assessments/new',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedHopeAssessmentsIdRoute = AuthedHopeAssessmentsIdImport.update({
  id: '/hope/assessments/$id',
  path: '/hope/assessments/$id',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedFilingsNoeNewRoute = AuthedFilingsNoeNewImport.update({
  id: '/filings/noe/new',
  path: '/filings/noe/new',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedPatientsPatientIdVisitsIndexRoute =
  AuthedPatientsPatientIdVisitsIndexImport.update({
    id: '/visits/',
    path: '/visits/',
    getParentRoute: () => AuthedPatientsPatientIdRoute,
  } as any)

const AuthedPatientsPatientIdIdgScheduleRoute =
  AuthedPatientsPatientIdIdgScheduleImport.update({
    id: '/idg/schedule',
    path: '/idg/schedule',
    getParentRoute: () => AuthedPatientsPatientIdRoute,
  } as any)

const AuthedPatientsPatientIdF2fNewRoute =
  AuthedPatientsPatientIdF2fNewImport.update({
    id: '/f2f/new',
    path: '/f2f/new',
    getParentRoute: () => AuthedPatientsPatientIdRoute,
  } as any)

const AuthedPatientsPatientIdEncountersEncounterIdVantageChartRoute =
  AuthedPatientsPatientIdEncountersEncounterIdVantageChartImport.update({
    id: '/encounters/$encounterId/vantage-chart',
    path: '/encounters/$encounterId/vantage-chart',
    getParentRoute: () => AuthedPatientsPatientIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/analytics/deficiency-trends': {
      id: '/_authed/analytics/deficiency-trends'
      path: '/analytics/deficiency-trends'
      fullPath: '/analytics/deficiency-trends'
      preLoaderRoute: typeof AuthedAnalyticsDeficiencyTrendsImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/analytics/scorecards': {
      id: '/_authed/analytics/scorecards'
      path: '/analytics/scorecards'
      fullPath: '/analytics/scorecards'
      preLoaderRoute: typeof AuthedAnalyticsScorecardsImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/billing/audit': {
      id: '/_authed/billing/audit'
      path: '/billing/audit'
      fullPath: '/billing/audit'
      preLoaderRoute: typeof AuthedBillingAuditImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/compliance/recert-queue': {
      id: '/_authed/compliance/recert-queue'
      path: '/compliance/recert-queue'
      fullPath: '/compliance/recert-queue'
      preLoaderRoute: typeof AuthedComplianceRecertQueueImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/filings/f2f-queue': {
      id: '/_authed/filings/f2f-queue'
      path: '/filings/f2f-queue'
      fullPath: '/filings/f2f-queue'
      preLoaderRoute: typeof AuthedFilingsF2fQueueImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/hope/dashboard': {
      id: '/_authed/hope/dashboard'
      path: '/hope/dashboard'
      fullPath: '/hope/dashboard'
      preLoaderRoute: typeof AuthedHopeDashboardImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/hope/submissions': {
      id: '/_authed/hope/submissions'
      path: '/hope/submissions'
      fullPath: '/hope/submissions'
      preLoaderRoute: typeof AuthedHopeSubmissionsImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/orders/inbox': {
      id: '/_authed/orders/inbox'
      path: '/orders/inbox'
      fullPath: '/orders/inbox'
      preLoaderRoute: typeof AuthedOrdersInboxImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/patients/$patientId': {
      id: '/_authed/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthedPatientsPatientIdImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/patients/new': {
      id: '/_authed/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof AuthedPatientsNewImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/alerts/': {
      id: '/_authed/alerts/'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthedAlertsIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/benefit-periods/': {
      id: '/_authed/benefit-periods/'
      path: '/benefit-periods'
      fullPath: '/benefit-periods'
      preLoaderRoute: typeof AuthedBenefitPeriodsIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/cap/': {
      id: '/_authed/cap/'
      path: '/cap'
      fullPath: '/cap'
      preLoaderRoute: typeof AuthedCapIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/chart-audit/': {
      id: '/_authed/chart-audit/'
      path: '/chart-audit'
      fullPath: '/chart-audit'
      preLoaderRoute: typeof AuthedChartAuditIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/filings/': {
      id: '/_authed/filings/'
      path: '/filings'
      fullPath: '/filings'
      preLoaderRoute: typeof AuthedFilingsIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/patients/': {
      id: '/_authed/patients/'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthedPatientsIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/qapi/': {
      id: '/_authed/qapi/'
      path: '/qapi'
      fullPath: '/qapi'
      preLoaderRoute: typeof AuthedQapiIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/review-queue/': {
      id: '/_authed/review-queue/'
      path: '/review-queue'
      fullPath: '/review-queue'
      preLoaderRoute: typeof AuthedReviewQueueIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/signatures/': {
      id: '/_authed/signatures/'
      path: '/signatures'
      fullPath: '/signatures'
      preLoaderRoute: typeof AuthedSignaturesIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/filings/noe/new': {
      id: '/_authed/filings/noe/new'
      path: '/filings/noe/new'
      fullPath: '/filings/noe/new'
      preLoaderRoute: typeof AuthedFilingsNoeNewImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/hope/assessments/$id': {
      id: '/_authed/hope/assessments/$id'
      path: '/hope/assessments/$id'
      fullPath: '/hope/assessments/$id'
      preLoaderRoute: typeof AuthedHopeAssessmentsIdImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/hope/assessments/new': {
      id: '/_authed/hope/assessments/new'
      path: '/hope/assessments/new'
      fullPath: '/hope/assessments/new'
      preLoaderRoute: typeof AuthedHopeAssessmentsNewImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/patients/$patientId/assessments': {
      id: '/_authed/patients/$patientId/assessments'
      path: '/assessments'
      fullPath: '/patients/$patientId/assessments'
      preLoaderRoute: typeof AuthedPatientsPatientIdAssessmentsImport
      parentRoute: typeof AuthedPatientsPatientIdImport
    }
    '/_authed/patients/$patientId/audit-export': {
      id: '/_authed/patients/$patientId/audit-export'
      path: '/audit-export'
      fullPath: '/patients/$patientId/audit-export'
      preLoaderRoute: typeof AuthedPatientsPatientIdAuditExportImport
      parentRoute: typeof AuthedPatientsPatientIdImport
    }
    '/_authed/patients/$patientId/care-team': {
      id: '/_authed/patients/$patientId/care-team'
      path: '/care-team'
      fullPath: '/patients/$patientId/care-team'
      preLoaderRoute: typeof AuthedPatientsPatientIdCareTeamImport
      parentRoute: typeof AuthedPatientsPatientIdImport
    }
    '/_authed/patients/$patientId/clinical-notes': {
      id: '/_authed/patients/$patientId/clinical-notes'
      path: '/clinical-notes'
      fullPath: '/patients/$patientId/clinical-notes'
      preLoaderRoute: typeof AuthedPatientsPatientIdClinicalNotesImport
      parentRoute: typeof AuthedPatientsPatientIdImport
    }
    '/_authed/patients/$patientId/documents': {
      id: '/_authed/patients/$patientId/documents'
      path: '/documents'
      fullPath: '/patients/$patientId/documents'
      preLoaderRoute: typeof AuthedPatientsPatientIdDocumentsImport
      parentRoute: typeof AuthedPatientsPatientIdImport
    }
    '/_authed/patients/$patientId/dose-spot': {
      id: '/_authed/patients/$patientId/dose-spot'
      path: '/dose-spot'
      fullPath: '/patients/$patientId/dose-spot'
      preLoaderRoute: typeof AuthedPatientsPatientIdDoseSpotImport
      parentRoute: typeof AuthedPatientsPatientIdImport
    }
    '/_authed/patients/$patientId/info': {
      id: '/_authed/patients/$patientId/info'
      path: '/info'
      fullPath: '/patients/$patientId/info'
      preLoaderRoute: typeof AuthedPatientsPatientIdInfoImport
      parentRoute: typeof AuthedPatientsPatientIdImport
    }
    '/_authed/patients/$patientId/medications': {
      id: '/_authed/patients/$patientId/medications'
      path: '/medications'
      fullPath: '/patients/$patientId/medications'
      preLoaderRoute: typeof AuthedPatientsPatientIdMedicationsImport
      parentRoute: typeof AuthedPatientsPatientIdImport
    }
    '/_authed/patients/$patientId/orders': {
      id: '/_authed/patients/$patientId/orders'
      path: '/orders'
      fullPath: '/patients/$patientId/orders'
      preLoaderRoute: typeof AuthedPatientsPatientIdOrdersImport
      parentRoute: typeof AuthedPatientsPatientIdImport
    }
    '/_authed/patients/$patientId/team-comm': {
      id: '/_authed/patients/$patientId/team-comm'
      path: '/team-comm'
      fullPath: '/patients/$patientId/team-comm'
      preLoaderRoute: typeof AuthedPatientsPatientIdTeamCommImport
      parentRoute: typeof AuthedPatientsPatientIdImport
    }
    '/_authed/settings/baa/$id': {
      id: '/_authed/settings/baa/$id'
      path: '/settings/baa/$id'
      fullPath: '/settings/baa/$id'
      preLoaderRoute: typeof AuthedSettingsBaaIdImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/settings/baa/new': {
      id: '/_authed/settings/baa/new'
      path: '/settings/baa/new'
      fullPath: '/settings/baa/new'
      preLoaderRoute: typeof AuthedSettingsBaaNewImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/hope/assessments/': {
      id: '/_authed/hope/assessments/'
      path: '/hope/assessments'
      fullPath: '/hope/assessments'
      preLoaderRoute: typeof AuthedHopeAssessmentsIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/patients/$patientId/': {
      id: '/_authed/patients/$patientId/'
      path: '/'
      fullPath: '/patients/$patientId/'
      preLoaderRoute: typeof AuthedPatientsPatientIdIndexImport
      parentRoute: typeof AuthedPatientsPatientIdImport
    }
    '/_authed/settings/baa/': {
      id: '/_authed/settings/baa/'
      path: '/settings/baa'
      fullPath: '/settings/baa'
      preLoaderRoute: typeof AuthedSettingsBaaIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/patients/$patientId/f2f/new': {
      id: '/_authed/patients/$patientId/f2f/new'
      path: '/f2f/new'
      fullPath: '/patients/$patientId/f2f/new'
      preLoaderRoute: typeof AuthedPatientsPatientIdF2fNewImport
      parentRoute: typeof AuthedPatientsPatientIdImport
    }
    '/_authed/patients/$patientId/idg/schedule': {
      id: '/_authed/patients/$patientId/idg/schedule'
      path: '/idg/schedule'
      fullPath: '/patients/$patientId/idg/schedule'
      preLoaderRoute: typeof AuthedPatientsPatientIdIdgScheduleImport
      parentRoute: typeof AuthedPatientsPatientIdImport
    }
    '/_authed/patients/$patientId/visits/': {
      id: '/_authed/patients/$patientId/visits/'
      path: '/visits'
      fullPath: '/patients/$patientId/visits'
      preLoaderRoute: typeof AuthedPatientsPatientIdVisitsIndexImport
      parentRoute: typeof AuthedPatientsPatientIdImport
    }
    '/_authed/patients/$patientId/encounters/$encounterId/vantage-chart': {
      id: '/_authed/patients/$patientId/encounters/$encounterId/vantage-chart'
      path: '/encounters/$encounterId/vantage-chart'
      fullPath: '/patients/$patientId/encounters/$encounterId/vantage-chart'
      preLoaderRoute: typeof AuthedPatientsPatientIdEncountersEncounterIdVantageChartImport
      parentRoute: typeof AuthedPatientsPatientIdImport
    }
  }
}

// Create and export the route tree

interface AuthedPatientsPatientIdRouteChildren {
  AuthedPatientsPatientIdAssessmentsRoute: typeof AuthedPatientsPatientIdAssessmentsRoute
  AuthedPatientsPatientIdAuditExportRoute: typeof AuthedPatientsPatientIdAuditExportRoute
  AuthedPatientsPatientIdCareTeamRoute: typeof AuthedPatientsPatientIdCareTeamRoute
  AuthedPatientsPatientIdClinicalNotesRoute: typeof AuthedPatientsPatientIdClinicalNotesRoute
  AuthedPatientsPatientIdDocumentsRoute: typeof AuthedPatientsPatientIdDocumentsRoute
  AuthedPatientsPatientIdDoseSpotRoute: typeof AuthedPatientsPatientIdDoseSpotRoute
  AuthedPatientsPatientIdInfoRoute: typeof AuthedPatientsPatientIdInfoRoute
  AuthedPatientsPatientIdMedicationsRoute: typeof AuthedPatientsPatientIdMedicationsRoute
  AuthedPatientsPatientIdOrdersRoute: typeof AuthedPatientsPatientIdOrdersRoute
  AuthedPatientsPatientIdTeamCommRoute: typeof AuthedPatientsPatientIdTeamCommRoute
  AuthedPatientsPatientIdIndexRoute: typeof AuthedPatientsPatientIdIndexRoute
  AuthedPatientsPatientIdF2fNewRoute: typeof AuthedPatientsPatientIdF2fNewRoute
  AuthedPatientsPatientIdIdgScheduleRoute: typeof AuthedPatientsPatientIdIdgScheduleRoute
  AuthedPatientsPatientIdVisitsIndexRoute: typeof AuthedPatientsPatientIdVisitsIndexRoute
  AuthedPatientsPatientIdEncountersEncounterIdVantageChartRoute: typeof AuthedPatientsPatientIdEncountersEncounterIdVantageChartRoute
}

const AuthedPatientsPatientIdRouteChildren: AuthedPatientsPatientIdRouteChildren =
  {
    AuthedPatientsPatientIdAssessmentsRoute:
      AuthedPatientsPatientIdAssessmentsRoute,
    AuthedPatientsPatientIdAuditExportRoute:
      AuthedPatientsPatientIdAuditExportRoute,
    AuthedPatientsPatientIdCareTeamRoute: AuthedPatientsPatientIdCareTeamRoute,
    AuthedPatientsPatientIdClinicalNotesRoute:
      AuthedPatientsPatientIdClinicalNotesRoute,
    AuthedPatientsPatientIdDocumentsRoute:
      AuthedPatientsPatientIdDocumentsRoute,
    AuthedPatientsPatientIdDoseSpotRoute: AuthedPatientsPatientIdDoseSpotRoute,
    AuthedPatientsPatientIdInfoRoute: AuthedPatientsPatientIdInfoRoute,
    AuthedPatientsPatientIdMedicationsRoute:
      AuthedPatientsPatientIdMedicationsRoute,
    AuthedPatientsPatientIdOrdersRoute: AuthedPatientsPatientIdOrdersRoute,
    AuthedPatientsPatientIdTeamCommRoute: AuthedPatientsPatientIdTeamCommRoute,
    AuthedPatientsPatientIdIndexRoute: AuthedPatientsPatientIdIndexRoute,
    AuthedPatientsPatientIdF2fNewRoute: AuthedPatientsPatientIdF2fNewRoute,
    AuthedPatientsPatientIdIdgScheduleRoute:
      AuthedPatientsPatientIdIdgScheduleRoute,
    AuthedPatientsPatientIdVisitsIndexRoute:
      AuthedPatientsPatientIdVisitsIndexRoute,
    AuthedPatientsPatientIdEncountersEncounterIdVantageChartRoute:
      AuthedPatientsPatientIdEncountersEncounterIdVantageChartRoute,
  }

const AuthedPatientsPatientIdRouteWithChildren =
  AuthedPatientsPatientIdRoute._addFileChildren(
    AuthedPatientsPatientIdRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedAnalyticsDeficiencyTrendsRoute: typeof AuthedAnalyticsDeficiencyTrendsRoute
  AuthedAnalyticsScorecardsRoute: typeof AuthedAnalyticsScorecardsRoute
  AuthedBillingAuditRoute: typeof AuthedBillingAuditRoute
  AuthedComplianceRecertQueueRoute: typeof AuthedComplianceRecertQueueRoute
  AuthedFilingsF2fQueueRoute: typeof AuthedFilingsF2fQueueRoute
  AuthedHopeDashboardRoute: typeof AuthedHopeDashboardRoute
  AuthedHopeSubmissionsRoute: typeof AuthedHopeSubmissionsRoute
  AuthedOrdersInboxRoute: typeof AuthedOrdersInboxRoute
  AuthedPatientsPatientIdRoute: typeof AuthedPatientsPatientIdRouteWithChildren
  AuthedPatientsNewRoute: typeof AuthedPatientsNewRoute
  AuthedAlertsIndexRoute: typeof AuthedAlertsIndexRoute
  AuthedBenefitPeriodsIndexRoute: typeof AuthedBenefitPeriodsIndexRoute
  AuthedCapIndexRoute: typeof AuthedCapIndexRoute
  AuthedChartAuditIndexRoute: typeof AuthedChartAuditIndexRoute
  AuthedFilingsIndexRoute: typeof AuthedFilingsIndexRoute
  AuthedPatientsIndexRoute: typeof AuthedPatientsIndexRoute
  AuthedQapiIndexRoute: typeof AuthedQapiIndexRoute
  AuthedReviewQueueIndexRoute: typeof AuthedReviewQueueIndexRoute
  AuthedSignaturesIndexRoute: typeof AuthedSignaturesIndexRoute
  AuthedFilingsNoeNewRoute: typeof AuthedFilingsNoeNewRoute
  AuthedHopeAssessmentsIdRoute: typeof AuthedHopeAssessmentsIdRoute
  AuthedHopeAssessmentsNewRoute: typeof AuthedHopeAssessmentsNewRoute
  AuthedSettingsBaaIdRoute: typeof AuthedSettingsBaaIdRoute
  AuthedSettingsBaaNewRoute: typeof AuthedSettingsBaaNewRoute
  AuthedHopeAssessmentsIndexRoute: typeof AuthedHopeAssessmentsIndexRoute
  AuthedSettingsBaaIndexRoute: typeof AuthedSettingsBaaIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedAnalyticsDeficiencyTrendsRoute: AuthedAnalyticsDeficiencyTrendsRoute,
  AuthedAnalyticsScorecardsRoute: AuthedAnalyticsScorecardsRoute,
  AuthedBillingAuditRoute: AuthedBillingAuditRoute,
  AuthedComplianceRecertQueueRoute: AuthedComplianceRecertQueueRoute,
  AuthedFilingsF2fQueueRoute: AuthedFilingsF2fQueueRoute,
  AuthedHopeDashboardRoute: AuthedHopeDashboardRoute,
  AuthedHopeSubmissionsRoute: AuthedHopeSubmissionsRoute,
  AuthedOrdersInboxRoute: AuthedOrdersInboxRoute,
  AuthedPatientsPatientIdRoute: AuthedPatientsPatientIdRouteWithChildren,
  AuthedPatientsNewRoute: AuthedPatientsNewRoute,
  AuthedAlertsIndexRoute: AuthedAlertsIndexRoute,
  AuthedBenefitPeriodsIndexRoute: AuthedBenefitPeriodsIndexRoute,
  AuthedCapIndexRoute: AuthedCapIndexRoute,
  AuthedChartAuditIndexRoute: AuthedChartAuditIndexRoute,
  AuthedFilingsIndexRoute: AuthedFilingsIndexRoute,
  AuthedPatientsIndexRoute: AuthedPatientsIndexRoute,
  AuthedQapiIndexRoute: AuthedQapiIndexRoute,
  AuthedReviewQueueIndexRoute: AuthedReviewQueueIndexRoute,
  AuthedSignaturesIndexRoute: AuthedSignaturesIndexRoute,
  AuthedFilingsNoeNewRoute: AuthedFilingsNoeNewRoute,
  AuthedHopeAssessmentsIdRoute: AuthedHopeAssessmentsIdRoute,
  AuthedHopeAssessmentsNewRoute: AuthedHopeAssessmentsNewRoute,
  AuthedSettingsBaaIdRoute: AuthedSettingsBaaIdRoute,
  AuthedSettingsBaaNewRoute: AuthedSettingsBaaNewRoute,
  AuthedHopeAssessmentsIndexRoute: AuthedHopeAssessmentsIndexRoute,
  AuthedSettingsBaaIndexRoute: AuthedSettingsBaaIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/analytics/deficiency-trends': typeof AuthedAnalyticsDeficiencyTrendsRoute
  '/analytics/scorecards': typeof AuthedAnalyticsScorecardsRoute
  '/billing/audit': typeof AuthedBillingAuditRoute
  '/compliance/recert-queue': typeof AuthedComplianceRecertQueueRoute
  '/filings/f2f-queue': typeof AuthedFilingsF2fQueueRoute
  '/hope/dashboard': typeof AuthedHopeDashboardRoute
  '/hope/submissions': typeof AuthedHopeSubmissionsRoute
  '/orders/inbox': typeof AuthedOrdersInboxRoute
  '/patients/$patientId': typeof AuthedPatientsPatientIdRouteWithChildren
  '/patients/new': typeof AuthedPatientsNewRoute
  '/alerts': typeof AuthedAlertsIndexRoute
  '/benefit-periods': typeof AuthedBenefitPeriodsIndexRoute
  '/cap': typeof AuthedCapIndexRoute
  '/chart-audit': typeof AuthedChartAuditIndexRoute
  '/filings': typeof AuthedFilingsIndexRoute
  '/patients': typeof AuthedPatientsIndexRoute
  '/qapi': typeof AuthedQapiIndexRoute
  '/review-queue': typeof AuthedReviewQueueIndexRoute
  '/signatures': typeof AuthedSignaturesIndexRoute
  '/filings/noe/new': typeof AuthedFilingsNoeNewRoute
  '/hope/assessments/$id': typeof AuthedHopeAssessmentsIdRoute
  '/hope/assessments/new': typeof AuthedHopeAssessmentsNewRoute
  '/patients/$patientId/assessments': typeof AuthedPatientsPatientIdAssessmentsRoute
  '/patients/$patientId/audit-export': typeof AuthedPatientsPatientIdAuditExportRoute
  '/patients/$patientId/care-team': typeof AuthedPatientsPatientIdCareTeamRoute
  '/patients/$patientId/clinical-notes': typeof AuthedPatientsPatientIdClinicalNotesRoute
  '/patients/$patientId/documents': typeof AuthedPatientsPatientIdDocumentsRoute
  '/patients/$patientId/dose-spot': typeof AuthedPatientsPatientIdDoseSpotRoute
  '/patients/$patientId/info': typeof AuthedPatientsPatientIdInfoRoute
  '/patients/$patientId/medications': typeof AuthedPatientsPatientIdMedicationsRoute
  '/patients/$patientId/orders': typeof AuthedPatientsPatientIdOrdersRoute
  '/patients/$patientId/team-comm': typeof AuthedPatientsPatientIdTeamCommRoute
  '/settings/baa/$id': typeof AuthedSettingsBaaIdRoute
  '/settings/baa/new': typeof AuthedSettingsBaaNewRoute
  '/hope/assessments': typeof AuthedHopeAssessmentsIndexRoute
  '/patients/$patientId/': typeof AuthedPatientsPatientIdIndexRoute
  '/settings/baa': typeof AuthedSettingsBaaIndexRoute
  '/patients/$patientId/f2f/new': typeof AuthedPatientsPatientIdF2fNewRoute
  '/patients/$patientId/idg/schedule': typeof AuthedPatientsPatientIdIdgScheduleRoute
  '/patients/$patientId/visits': typeof AuthedPatientsPatientIdVisitsIndexRoute
  '/patients/$patientId/encounters/$encounterId/vantage-chart': typeof AuthedPatientsPatientIdEncountersEncounterIdVantageChartRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/analytics/deficiency-trends': typeof AuthedAnalyticsDeficiencyTrendsRoute
  '/analytics/scorecards': typeof AuthedAnalyticsScorecardsRoute
  '/billing/audit': typeof AuthedBillingAuditRoute
  '/compliance/recert-queue': typeof AuthedComplianceRecertQueueRoute
  '/filings/f2f-queue': typeof AuthedFilingsF2fQueueRoute
  '/hope/dashboard': typeof AuthedHopeDashboardRoute
  '/hope/submissions': typeof AuthedHopeSubmissionsRoute
  '/orders/inbox': typeof AuthedOrdersInboxRoute
  '/patients/new': typeof AuthedPatientsNewRoute
  '/alerts': typeof AuthedAlertsIndexRoute
  '/benefit-periods': typeof AuthedBenefitPeriodsIndexRoute
  '/cap': typeof AuthedCapIndexRoute
  '/chart-audit': typeof AuthedChartAuditIndexRoute
  '/filings': typeof AuthedFilingsIndexRoute
  '/patients': typeof AuthedPatientsIndexRoute
  '/qapi': typeof AuthedQapiIndexRoute
  '/review-queue': typeof AuthedReviewQueueIndexRoute
  '/signatures': typeof AuthedSignaturesIndexRoute
  '/filings/noe/new': typeof AuthedFilingsNoeNewRoute
  '/hope/assessments/$id': typeof AuthedHopeAssessmentsIdRoute
  '/hope/assessments/new': typeof AuthedHopeAssessmentsNewRoute
  '/patients/$patientId/assessments': typeof AuthedPatientsPatientIdAssessmentsRoute
  '/patients/$patientId/audit-export': typeof AuthedPatientsPatientIdAuditExportRoute
  '/patients/$patientId/care-team': typeof AuthedPatientsPatientIdCareTeamRoute
  '/patients/$patientId/clinical-notes': typeof AuthedPatientsPatientIdClinicalNotesRoute
  '/patients/$patientId/documents': typeof AuthedPatientsPatientIdDocumentsRoute
  '/patients/$patientId/dose-spot': typeof AuthedPatientsPatientIdDoseSpotRoute
  '/patients/$patientId/info': typeof AuthedPatientsPatientIdInfoRoute
  '/patients/$patientId/medications': typeof AuthedPatientsPatientIdMedicationsRoute
  '/patients/$patientId/orders': typeof AuthedPatientsPatientIdOrdersRoute
  '/patients/$patientId/team-comm': typeof AuthedPatientsPatientIdTeamCommRoute
  '/settings/baa/$id': typeof AuthedSettingsBaaIdRoute
  '/settings/baa/new': typeof AuthedSettingsBaaNewRoute
  '/hope/assessments': typeof AuthedHopeAssessmentsIndexRoute
  '/patients/$patientId': typeof AuthedPatientsPatientIdIndexRoute
  '/settings/baa': typeof AuthedSettingsBaaIndexRoute
  '/patients/$patientId/f2f/new': typeof AuthedPatientsPatientIdF2fNewRoute
  '/patients/$patientId/idg/schedule': typeof AuthedPatientsPatientIdIdgScheduleRoute
  '/patients/$patientId/visits': typeof AuthedPatientsPatientIdVisitsIndexRoute
  '/patients/$patientId/encounters/$encounterId/vantage-chart': typeof AuthedPatientsPatientIdEncountersEncounterIdVantageChartRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/analytics/deficiency-trends': typeof AuthedAnalyticsDeficiencyTrendsRoute
  '/_authed/analytics/scorecards': typeof AuthedAnalyticsScorecardsRoute
  '/_authed/billing/audit': typeof AuthedBillingAuditRoute
  '/_authed/compliance/recert-queue': typeof AuthedComplianceRecertQueueRoute
  '/_authed/filings/f2f-queue': typeof AuthedFilingsF2fQueueRoute
  '/_authed/hope/dashboard': typeof AuthedHopeDashboardRoute
  '/_authed/hope/submissions': typeof AuthedHopeSubmissionsRoute
  '/_authed/orders/inbox': typeof AuthedOrdersInboxRoute
  '/_authed/patients/$patientId': typeof AuthedPatientsPatientIdRouteWithChildren
  '/_authed/patients/new': typeof AuthedPatientsNewRoute
  '/_authed/alerts/': typeof AuthedAlertsIndexRoute
  '/_authed/benefit-periods/': typeof AuthedBenefitPeriodsIndexRoute
  '/_authed/cap/': typeof AuthedCapIndexRoute
  '/_authed/chart-audit/': typeof AuthedChartAuditIndexRoute
  '/_authed/filings/': typeof AuthedFilingsIndexRoute
  '/_authed/patients/': typeof AuthedPatientsIndexRoute
  '/_authed/qapi/': typeof AuthedQapiIndexRoute
  '/_authed/review-queue/': typeof AuthedReviewQueueIndexRoute
  '/_authed/signatures/': typeof AuthedSignaturesIndexRoute
  '/_authed/filings/noe/new': typeof AuthedFilingsNoeNewRoute
  '/_authed/hope/assessments/$id': typeof AuthedHopeAssessmentsIdRoute
  '/_authed/hope/assessments/new': typeof AuthedHopeAssessmentsNewRoute
  '/_authed/patients/$patientId/assessments': typeof AuthedPatientsPatientIdAssessmentsRoute
  '/_authed/patients/$patientId/audit-export': typeof AuthedPatientsPatientIdAuditExportRoute
  '/_authed/patients/$patientId/care-team': typeof AuthedPatientsPatientIdCareTeamRoute
  '/_authed/patients/$patientId/clinical-notes': typeof AuthedPatientsPatientIdClinicalNotesRoute
  '/_authed/patients/$patientId/documents': typeof AuthedPatientsPatientIdDocumentsRoute
  '/_authed/patients/$patientId/dose-spot': typeof AuthedPatientsPatientIdDoseSpotRoute
  '/_authed/patients/$patientId/info': typeof AuthedPatientsPatientIdInfoRoute
  '/_authed/patients/$patientId/medications': typeof AuthedPatientsPatientIdMedicationsRoute
  '/_authed/patients/$patientId/orders': typeof AuthedPatientsPatientIdOrdersRoute
  '/_authed/patients/$patientId/team-comm': typeof AuthedPatientsPatientIdTeamCommRoute
  '/_authed/settings/baa/$id': typeof AuthedSettingsBaaIdRoute
  '/_authed/settings/baa/new': typeof AuthedSettingsBaaNewRoute
  '/_authed/hope/assessments/': typeof AuthedHopeAssessmentsIndexRoute
  '/_authed/patients/$patientId/': typeof AuthedPatientsPatientIdIndexRoute
  '/_authed/settings/baa/': typeof AuthedSettingsBaaIndexRoute
  '/_authed/patients/$patientId/f2f/new': typeof AuthedPatientsPatientIdF2fNewRoute
  '/_authed/patients/$patientId/idg/schedule': typeof AuthedPatientsPatientIdIdgScheduleRoute
  '/_authed/patients/$patientId/visits/': typeof AuthedPatientsPatientIdVisitsIndexRoute
  '/_authed/patients/$patientId/encounters/$encounterId/vantage-chart': typeof AuthedPatientsPatientIdEncountersEncounterIdVantageChartRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/dashboard'
    | '/analytics/deficiency-trends'
    | '/analytics/scorecards'
    | '/billing/audit'
    | '/compliance/recert-queue'
    | '/filings/f2f-queue'
    | '/hope/dashboard'
    | '/hope/submissions'
    | '/orders/inbox'
    | '/patients/$patientId'
    | '/patients/new'
    | '/alerts'
    | '/benefit-periods'
    | '/cap'
    | '/chart-audit'
    | '/filings'
    | '/patients'
    | '/qapi'
    | '/review-queue'
    | '/signatures'
    | '/filings/noe/new'
    | '/hope/assessments/$id'
    | '/hope/assessments/new'
    | '/patients/$patientId/assessments'
    | '/patients/$patientId/audit-export'
    | '/patients/$patientId/care-team'
    | '/patients/$patientId/clinical-notes'
    | '/patients/$patientId/documents'
    | '/patients/$patientId/dose-spot'
    | '/patients/$patientId/info'
    | '/patients/$patientId/medications'
    | '/patients/$patientId/orders'
    | '/patients/$patientId/team-comm'
    | '/settings/baa/$id'
    | '/settings/baa/new'
    | '/hope/assessments'
    | '/patients/$patientId/'
    | '/settings/baa'
    | '/patients/$patientId/f2f/new'
    | '/patients/$patientId/idg/schedule'
    | '/patients/$patientId/visits'
    | '/patients/$patientId/encounters/$encounterId/vantage-chart'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/dashboard'
    | '/analytics/deficiency-trends'
    | '/analytics/scorecards'
    | '/billing/audit'
    | '/compliance/recert-queue'
    | '/filings/f2f-queue'
    | '/hope/dashboard'
    | '/hope/submissions'
    | '/orders/inbox'
    | '/patients/new'
    | '/alerts'
    | '/benefit-periods'
    | '/cap'
    | '/chart-audit'
    | '/filings'
    | '/patients'
    | '/qapi'
    | '/review-queue'
    | '/signatures'
    | '/filings/noe/new'
    | '/hope/assessments/$id'
    | '/hope/assessments/new'
    | '/patients/$patientId/assessments'
    | '/patients/$patientId/audit-export'
    | '/patients/$patientId/care-team'
    | '/patients/$patientId/clinical-notes'
    | '/patients/$patientId/documents'
    | '/patients/$patientId/dose-spot'
    | '/patients/$patientId/info'
    | '/patients/$patientId/medications'
    | '/patients/$patientId/orders'
    | '/patients/$patientId/team-comm'
    | '/settings/baa/$id'
    | '/settings/baa/new'
    | '/hope/assessments'
    | '/patients/$patientId'
    | '/settings/baa'
    | '/patients/$patientId/f2f/new'
    | '/patients/$patientId/idg/schedule'
    | '/patients/$patientId/visits'
    | '/patients/$patientId/encounters/$encounterId/vantage-chart'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/analytics/deficiency-trends'
    | '/_authed/analytics/scorecards'
    | '/_authed/billing/audit'
    | '/_authed/compliance/recert-queue'
    | '/_authed/filings/f2f-queue'
    | '/_authed/hope/dashboard'
    | '/_authed/hope/submissions'
    | '/_authed/orders/inbox'
    | '/_authed/patients/$patientId'
    | '/_authed/patients/new'
    | '/_authed/alerts/'
    | '/_authed/benefit-periods/'
    | '/_authed/cap/'
    | '/_authed/chart-audit/'
    | '/_authed/filings/'
    | '/_authed/patients/'
    | '/_authed/qapi/'
    | '/_authed/review-queue/'
    | '/_authed/signatures/'
    | '/_authed/filings/noe/new'
    | '/_authed/hope/assessments/$id'
    | '/_authed/hope/assessments/new'
    | '/_authed/patients/$patientId/assessments'
    | '/_authed/patients/$patientId/audit-export'
    | '/_authed/patients/$patientId/care-team'
    | '/_authed/patients/$patientId/clinical-notes'
    | '/_authed/patients/$patientId/documents'
    | '/_authed/patients/$patientId/dose-spot'
    | '/_authed/patients/$patientId/info'
    | '/_authed/patients/$patientId/medications'
    | '/_authed/patients/$patientId/orders'
    | '/_authed/patients/$patientId/team-comm'
    | '/_authed/settings/baa/$id'
    | '/_authed/settings/baa/new'
    | '/_authed/hope/assessments/'
    | '/_authed/patients/$patientId/'
    | '/_authed/settings/baa/'
    | '/_authed/patients/$patientId/f2f/new'
    | '/_authed/patients/$patientId/idg/schedule'
    | '/_authed/patients/$patientId/visits/'
    | '/_authed/patients/$patientId/encounters/$encounterId/vantage-chart'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authed",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/dashboard",
        "/_authed/analytics/deficiency-trends",
        "/_authed/analytics/scorecards",
        "/_authed/billing/audit",
        "/_authed/compliance/recert-queue",
        "/_authed/filings/f2f-queue",
        "/_authed/hope/dashboard",
        "/_authed/hope/submissions",
        "/_authed/orders/inbox",
        "/_authed/patients/$patientId",
        "/_authed/patients/new",
        "/_authed/alerts/",
        "/_authed/benefit-periods/",
        "/_authed/cap/",
        "/_authed/chart-audit/",
        "/_authed/filings/",
        "/_authed/patients/",
        "/_authed/qapi/",
        "/_authed/review-queue/",
        "/_authed/signatures/",
        "/_authed/filings/noe/new",
        "/_authed/hope/assessments/$id",
        "/_authed/hope/assessments/new",
        "/_authed/settings/baa/$id",
        "/_authed/settings/baa/new",
        "/_authed/hope/assessments/",
        "/_authed/settings/baa/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authed/dashboard": {
      "filePath": "_authed/dashboard.tsx",
      "parent": "/_authed"
    },
    "/_authed/analytics/deficiency-trends": {
      "filePath": "_authed/analytics/deficiency-trends.tsx",
      "parent": "/_authed"
    },
    "/_authed/analytics/scorecards": {
      "filePath": "_authed/analytics/scorecards.tsx",
      "parent": "/_authed"
    },
    "/_authed/billing/audit": {
      "filePath": "_authed/billing/audit.tsx",
      "parent": "/_authed"
    },
    "/_authed/compliance/recert-queue": {
      "filePath": "_authed/compliance/recert-queue.tsx",
      "parent": "/_authed"
    },
    "/_authed/filings/f2f-queue": {
      "filePath": "_authed/filings/f2f-queue.tsx",
      "parent": "/_authed"
    },
    "/_authed/hope/dashboard": {
      "filePath": "_authed/hope/dashboard.tsx",
      "parent": "/_authed"
    },
    "/_authed/hope/submissions": {
      "filePath": "_authed/hope/submissions.tsx",
      "parent": "/_authed"
    },
    "/_authed/orders/inbox": {
      "filePath": "_authed/orders/inbox.tsx",
      "parent": "/_authed"
    },
    "/_authed/patients/$patientId": {
      "filePath": "_authed/patients/$patientId.tsx",
      "parent": "/_authed",
      "children": [
        "/_authed/patients/$patientId/assessments",
        "/_authed/patients/$patientId/audit-export",
        "/_authed/patients/$patientId/care-team",
        "/_authed/patients/$patientId/clinical-notes",
        "/_authed/patients/$patientId/documents",
        "/_authed/patients/$patientId/dose-spot",
        "/_authed/patients/$patientId/info",
        "/_authed/patients/$patientId/medications",
        "/_authed/patients/$patientId/orders",
        "/_authed/patients/$patientId/team-comm",
        "/_authed/patients/$patientId/",
        "/_authed/patients/$patientId/f2f/new",
        "/_authed/patients/$patientId/idg/schedule",
        "/_authed/patients/$patientId/visits/",
        "/_authed/patients/$patientId/encounters/$encounterId/vantage-chart"
      ]
    },
    "/_authed/patients/new": {
      "filePath": "_authed/patients/new.tsx",
      "parent": "/_authed"
    },
    "/_authed/alerts/": {
      "filePath": "_authed/alerts/index.tsx",
      "parent": "/_authed"
    },
    "/_authed/benefit-periods/": {
      "filePath": "_authed/benefit-periods/index.tsx",
      "parent": "/_authed"
    },
    "/_authed/cap/": {
      "filePath": "_authed/cap/index.tsx",
      "parent": "/_authed"
    },
    "/_authed/chart-audit/": {
      "filePath": "_authed/chart-audit/index.tsx",
      "parent": "/_authed"
    },
    "/_authed/filings/": {
      "filePath": "_authed/filings/index.tsx",
      "parent": "/_authed"
    },
    "/_authed/patients/": {
      "filePath": "_authed/patients/index.tsx",
      "parent": "/_authed"
    },
    "/_authed/qapi/": {
      "filePath": "_authed/qapi/index.tsx",
      "parent": "/_authed"
    },
    "/_authed/review-queue/": {
      "filePath": "_authed/review-queue/index.tsx",
      "parent": "/_authed"
    },
    "/_authed/signatures/": {
      "filePath": "_authed/signatures/index.tsx",
      "parent": "/_authed"
    },
    "/_authed/filings/noe/new": {
      "filePath": "_authed/filings/noe/new.tsx",
      "parent": "/_authed"
    },
    "/_authed/hope/assessments/$id": {
      "filePath": "_authed/hope/assessments/$id.tsx",
      "parent": "/_authed"
    },
    "/_authed/hope/assessments/new": {
      "filePath": "_authed/hope/assessments/new.tsx",
      "parent": "/_authed"
    },
    "/_authed/patients/$patientId/assessments": {
      "filePath": "_authed/patients/$patientId/assessments.tsx",
      "parent": "/_authed/patients/$patientId"
    },
    "/_authed/patients/$patientId/audit-export": {
      "filePath": "_authed/patients/$patientId/audit-export.tsx",
      "parent": "/_authed/patients/$patientId"
    },
    "/_authed/patients/$patientId/care-team": {
      "filePath": "_authed/patients/$patientId/care-team.tsx",
      "parent": "/_authed/patients/$patientId"
    },
    "/_authed/patients/$patientId/clinical-notes": {
      "filePath": "_authed/patients/$patientId/clinical-notes.tsx",
      "parent": "/_authed/patients/$patientId"
    },
    "/_authed/patients/$patientId/documents": {
      "filePath": "_authed/patients/$patientId/documents.tsx",
      "parent": "/_authed/patients/$patientId"
    },
    "/_authed/patients/$patientId/dose-spot": {
      "filePath": "_authed/patients/$patientId/dose-spot.tsx",
      "parent": "/_authed/patients/$patientId"
    },
    "/_authed/patients/$patientId/info": {
      "filePath": "_authed/patients/$patientId/info.tsx",
      "parent": "/_authed/patients/$patientId"
    },
    "/_authed/patients/$patientId/medications": {
      "filePath": "_authed/patients/$patientId/medications.tsx",
      "parent": "/_authed/patients/$patientId"
    },
    "/_authed/patients/$patientId/orders": {
      "filePath": "_authed/patients/$patientId/orders.tsx",
      "parent": "/_authed/patients/$patientId"
    },
    "/_authed/patients/$patientId/team-comm": {
      "filePath": "_authed/patients/$patientId/team-comm.tsx",
      "parent": "/_authed/patients/$patientId"
    },
    "/_authed/settings/baa/$id": {
      "filePath": "_authed/settings/baa/$id.tsx",
      "parent": "/_authed"
    },
    "/_authed/settings/baa/new": {
      "filePath": "_authed/settings/baa/new.tsx",
      "parent": "/_authed"
    },
    "/_authed/hope/assessments/": {
      "filePath": "_authed/hope/assessments/index.tsx",
      "parent": "/_authed"
    },
    "/_authed/patients/$patientId/": {
      "filePath": "_authed/patients/$patientId/index.tsx",
      "parent": "/_authed/patients/$patientId"
    },
    "/_authed/settings/baa/": {
      "filePath": "_authed/settings/baa/index.tsx",
      "parent": "/_authed"
    },
    "/_authed/patients/$patientId/f2f/new": {
      "filePath": "_authed/patients/$patientId/f2f/new.tsx",
      "parent": "/_authed/patients/$patientId"
    },
    "/_authed/patients/$patientId/idg/schedule": {
      "filePath": "_authed/patients/$patientId/idg/schedule.tsx",
      "parent": "/_authed/patients/$patientId"
    },
    "/_authed/patients/$patientId/visits/": {
      "filePath": "_authed/patients/$patientId/visits/index.tsx",
      "parent": "/_authed/patients/$patientId"
    },
    "/_authed/patients/$patientId/encounters/$encounterId/vantage-chart": {
      "filePath": "_authed/patients/$patientId/encounters/$encounterId/vantage-chart.tsx",
      "parent": "/_authed/patients/$patientId"
    }
  }
}
ROUTE_MANIFEST_END */
