// routeTree.gen.ts
// AUTO-GENERATED by TanStack Router — do not edit manually.
// This stub is replaced when `vinxi dev` or `vinxi build` runs.
// @ts-nocheck

import { Route as rootRoute } from "./routes/__root";
import { Route as authedRoute } from "./routes/_authed";
import { Route as authedAlertsIndexRoute } from "./routes/_authed/alerts/index";
import { Route as authedBenefitPeriodsIndexRoute } from "./routes/_authed/benefit-periods/index";
import { Route as authedCapIndexRoute } from "./routes/_authed/cap/index";
import { Route as authedComplianceRecertQueueRoute } from "./routes/_authed/compliance/recert-queue";
import { Route as authedDashboardRoute } from "./routes/_authed/dashboard";
import { Route as authedFilingsF2FQueueRoute } from "./routes/_authed/filings/f2f-queue";
import { Route as authedFilingsIndexRoute } from "./routes/_authed/filings/index";
import { Route as authedHopeAssessmentsIdRoute } from "./routes/_authed/hope/assessments/$id";
import { Route as authedHopeAssessmentsIndexRoute } from "./routes/_authed/hope/assessments/index";
import { Route as authedHopeAssessmentsNewRoute } from "./routes/_authed/hope/assessments/new";
import { Route as authedHopeDashboardRoute } from "./routes/_authed/hope/dashboard";
import { Route as authedHopeSubmissionsRoute } from "./routes/_authed/hope/submissions";
import { Route as authedPatientsPatientIdRoute } from "./routes/_authed/patients/$patientId";
import { Route as authedPatientsPatientIdEncountersEncounterIdVantageChartRoute } from "./routes/_authed/patients/$patientId/encounters/$encounterId/vantage-chart";
import { Route as authedPatientsPatientIdF2FNewRoute } from "./routes/_authed/patients/$patientId/f2f/new";
import { Route as authedPatientsPatientIdIdgScheduleRoute } from "./routes/_authed/patients/$patientId/idg/schedule";
import { Route as authedPatientsPatientIdVisitsIndexRoute } from "./routes/_authed/patients/$patientId/visits/index";
import { Route as authedPatientsIndexRoute } from "./routes/_authed/patients/index";
import { Route as authedReviewQueueIndexRoute } from "./routes/_authed/review-queue/index";
import { Route as authedSignaturesIndexRoute } from "./routes/_authed/signatures/index";
import { Route as IndexRoute } from "./routes/index";
import { Route as LoginRoute } from "./routes/login";

// Assemble the route tree
const authedPatientsPatientIdRouteWithChildren = authedPatientsPatientIdRoute.addChildren({
  authedPatientsPatientIdIdgScheduleRoute,
  authedPatientsPatientIdEncountersEncounterIdVantageChartRoute,
  authedPatientsPatientIdVisitsIndexRoute,
  authedPatientsPatientIdF2FNewRoute,
});

const authedRouteWithChildren = authedRoute.addChildren({
  authedDashboardRoute,
  authedAlertsIndexRoute,
  authedReviewQueueIndexRoute,
  authedPatientsIndexRoute,
  authedPatientsPatientIdRoute: authedPatientsPatientIdRouteWithChildren,
  authedHopeAssessmentsIndexRoute,
  authedHopeAssessmentsNewRoute,
  authedHopeAssessmentsIdRoute,
  authedHopeDashboardRoute,
  authedHopeSubmissionsRoute,
  authedFilingsIndexRoute,
  authedFilingsF2FQueueRoute,
  authedCapIndexRoute,
  authedBenefitPeriodsIndexRoute,
  authedComplianceRecertQueueRoute,
  authedSignaturesIndexRoute,
});

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LoginRoute,
  authedRoute: authedRouteWithChildren,
});

// Module augmentation — makes createFileRoute(path) type-safe across the project
declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRoute;
      parentRoute: typeof rootRoute;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRoute;
      parentRoute: typeof rootRoute;
    };
    "/_authed": {
      id: "/_authed";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof authedRoute;
      parentRoute: typeof rootRoute;
    };
    "/_authed/dashboard": {
      id: "/_authed/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof authedDashboardRoute;
      parentRoute: typeof authedRoute;
    };
    "/_authed/alerts/": {
      id: "/_authed/alerts/";
      path: "/alerts";
      fullPath: "/alerts";
      preLoaderRoute: typeof authedAlertsIndexRoute;
      parentRoute: typeof authedRoute;
    };
    "/_authed/review-queue/": {
      id: "/_authed/review-queue/";
      path: "/review-queue";
      fullPath: "/review-queue";
      preLoaderRoute: typeof authedReviewQueueIndexRoute;
      parentRoute: typeof authedRoute;
    };
    "/_authed/patients/": {
      id: "/_authed/patients/";
      path: "/patients";
      fullPath: "/patients";
      preLoaderRoute: typeof authedPatientsIndexRoute;
      parentRoute: typeof authedRoute;
    };
    "/_authed/patients/$patientId": {
      id: "/_authed/patients/$patientId";
      path: "/patients/$patientId";
      fullPath: "/patients/$patientId";
      preLoaderRoute: typeof authedPatientsPatientIdRoute;
      parentRoute: typeof authedRoute;
    };
    "/_authed/patients/$patientId/idg/schedule": {
      id: "/_authed/patients/$patientId/idg/schedule";
      path: "/idg/schedule";
      fullPath: "/patients/$patientId/idg/schedule";
      preLoaderRoute: typeof authedPatientsPatientIdIdgScheduleRoute;
      parentRoute: typeof authedPatientsPatientIdRoute;
    };
    "/_authed/patients/$patientId/encounters/$encounterId/vantage-chart": {
      id: "/_authed/patients/$patientId/encounters/$encounterId/vantage-chart";
      path: "/encounters/$encounterId/vantage-chart";
      fullPath: "/patients/$patientId/encounters/$encounterId/vantage-chart";
      preLoaderRoute: typeof authedPatientsPatientIdEncountersEncounterIdVantageChartRoute;
      parentRoute: typeof authedPatientsPatientIdRoute;
    };
    "/_authed/patients/$patientId/visits/": {
      id: "/_authed/patients/$patientId/visits/";
      path: "/visits";
      fullPath: "/patients/$patientId/visits";
      preLoaderRoute: typeof authedPatientsPatientIdVisitsIndexRoute;
      parentRoute: typeof authedPatientsPatientIdRoute;
    };
    "/_authed/patients/$patientId/f2f/new": {
      id: "/_authed/patients/$patientId/f2f/new";
      path: "/f2f/new";
      fullPath: "/patients/$patientId/f2f/new";
      preLoaderRoute: typeof authedPatientsPatientIdF2FNewRoute;
      parentRoute: typeof authedPatientsPatientIdRoute;
    };
    "/_authed/hope/assessments/": {
      id: "/_authed/hope/assessments/";
      path: "/hope/assessments";
      fullPath: "/hope/assessments";
      preLoaderRoute: typeof authedHopeAssessmentsIndexRoute;
      parentRoute: typeof authedRoute;
    };
    "/_authed/hope/assessments/new": {
      id: "/_authed/hope/assessments/new";
      path: "/hope/assessments/new";
      fullPath: "/hope/assessments/new";
      preLoaderRoute: typeof authedHopeAssessmentsNewRoute;
      parentRoute: typeof authedRoute;
    };
    "/_authed/hope/assessments/$id": {
      id: "/_authed/hope/assessments/$id";
      path: "/hope/assessments/$id";
      fullPath: "/hope/assessments/$id";
      preLoaderRoute: typeof authedHopeAssessmentsIdRoute;
      parentRoute: typeof authedRoute;
    };
    "/_authed/hope/dashboard": {
      id: "/_authed/hope/dashboard";
      path: "/hope/dashboard";
      fullPath: "/hope/dashboard";
      preLoaderRoute: typeof authedHopeDashboardRoute;
      parentRoute: typeof authedRoute;
    };
    "/_authed/hope/submissions": {
      id: "/_authed/hope/submissions";
      path: "/hope/submissions";
      fullPath: "/hope/submissions";
      preLoaderRoute: typeof authedHopeSubmissionsRoute;
      parentRoute: typeof authedRoute;
    };
    "/_authed/filings/": {
      id: "/_authed/filings/";
      path: "/filings";
      fullPath: "/filings";
      preLoaderRoute: typeof authedFilingsIndexRoute;
      parentRoute: typeof authedRoute;
    };
    "/_authed/filings/f2f-queue": {
      id: "/_authed/filings/f2f-queue";
      path: "/filings/f2f-queue";
      fullPath: "/filings/f2f-queue";
      preLoaderRoute: typeof authedFilingsF2FQueueRoute;
      parentRoute: typeof authedRoute;
    };
    "/_authed/cap/": {
      id: "/_authed/cap/";
      path: "/cap";
      fullPath: "/cap";
      preLoaderRoute: typeof authedCapIndexRoute;
      parentRoute: typeof authedRoute;
    };
    "/_authed/benefit-periods/": {
      id: "/_authed/benefit-periods/";
      path: "/benefit-periods";
      fullPath: "/benefit-periods";
      preLoaderRoute: typeof authedBenefitPeriodsIndexRoute;
      parentRoute: typeof authedRoute;
    };
    "/_authed/compliance/recert-queue": {
      id: "/_authed/compliance/recert-queue";
      path: "/compliance/recert-queue";
      fullPath: "/compliance/recert-queue";
      preLoaderRoute: typeof authedComplianceRecertQueueRoute;
      parentRoute: typeof authedRoute;
    };
    "/_authed/signatures/": {
      id: "/_authed/signatures/";
      path: "/signatures";
      fullPath: "/signatures";
      preLoaderRoute: typeof authedSignaturesIndexRoute;
      parentRoute: typeof authedRoute;
    };
  }
}
